version: "3.7"
services:
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=joe
            - MYSQL_PASSWORD=eoj
            - MYSQL_DATABASE=test

    admin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=yes
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=joe
            - PMA_PASSWORD=eoj
            - PMA_ABSOLUTE_URI=http://${HOSTNAME}/admin/

    entry:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d:/etc/nginx/conf.d/
        command: nginx -g 'daemon off;'

